GameBg/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@index')->name('home');

Auth::routes();

Route::resource('game', 'Admin\GameController', ['only' => ['create', 'store', 'edit', 'update', 'destroy']]);
Route::resource('game', 'GameController', ['only' => ['show', 'index']]);

Route::resource('user', 'UserController', ['only' => ['show', 'edit', 'update']]);
Route::resource('user', 'Admin\UserController', ['only' => ['destroy']]);

Route::resource('category', 'CategoryController', ['only' => ['store', 'update', 'destroy']]);

Route::post('/user/games/{game}/add', 'UserGameController@store')->name('user.games.add');
Route::delete('/user/games/{game}/remove', 'UserGameController@destroy')->name('user.games.remove');

Route::post('/user/friends/{user}/add', 'UserFriendController@store')->name('user.friends.add');
Route::delete('/user/friends/{user}/remove', 'UserFriendController@destroy')->name('user.friends.remove');

Route::post('/user/{user}/messages/add', 'UserMessageController@store')->name('user.messages.add');
Route::get('/user/{user}/messages', 'UserMessageController@index')->name('user.messages.index');

Route::get('/password/{user}/edit', 'ChangePasswordController@edit')->name('user.password.edit');
Route::put('/password/{user}/update', 'ChangePasswordController@update')->name('user.password.update');

Route::get('/search-user', 'SearchUserController@index')->name('user.search.index');

Route::get('/admin', 'AdminController@show')->name('admin.show');

GameBg/resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'GameBG') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" type="text/javascript"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js" type="text/javascript"></script>
    @yield('scripts')

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    @yield("styles")
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ route('game.index') }}">
                    GameBG
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            @if (auth()->user()->isAdmin())
                            <li class="nav-item">
                                <a class="nav-link" href="{{route('admin.show')}}"><b>Admin Panel</b></a>
                            </li>
                            @endif
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{route('user.show', auth()->user()->username)}}">
                                        My profile
                                    </a>
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>