GameBg/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@index')->name('home');

Auth::routes();

Route::resource('game', 'Admin\GameController', ['only' => ['create', 'store', 'edit', 'update', 'destroy']]);
Route::resource('game', 'GameController', ['only' => ['show', 'index']]);

Route::resource('user', 'UserController', ['only' => ['show', 'edit', 'update']]);
Route::resource('user', 'Admin\UserController', ['only' => ['destroy']]);

Route::resource('category', 'CategoryController', ['only' => ['store', 'update', 'destroy']]);

Route::post('/user/games/{game}/add', 'UserGameController@store')->name('user.games.add');
Route::delete('/user/games/{game}/remove', 'UserGameController@destroy')->name('user.games.remove');

Route::post('/user/friends/{user}/add', 'UserFriendController@store')->name('user.friends.add');
Route::delete('/user/friends/{user}/remove', 'UserFriendController@destroy')->name('user.friends.remove');

Route::post('/user/{user}/messages/add', 'UserMessageController@store')->name('user.messages.add');
Route::get('/user/{user}/messages', 'UserMessageController@index')->name('user.messages.index');

Route::get('/password/{user}/edit', 'ChangePasswordController@edit')->name('user.password.edit');
Route::put('/password/{user}/update', 'ChangePasswordController@update')->name('user.password.update');

Route::get('/search-user', 'SearchUserController@index')->name('user.search.index');

Route::get('/admin', 'AdminController@show')->name('admin.show');

GameBg/app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\Storage;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'username', 'image'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function games()
    {
        return $this->belongsToMany(Game::class,
            'players_games',
            'player_id',
            'game_id');
    }

    public function addGame(Game $game)
    {
        return $this->games()->save($game);
    }

    public function removeGame(Game $game)
    {
        return $this->games()->detach($game);
    }

    public function acceptedFriends()
    {
        return $this->belongsToMany(User::class,
            'friends',
            'added_friend_id',
            'user_id');

    }

    public function addedFriends()
    {
        return $this->belongsToMany(User::class,
            'friends',
            'user_id',
            'added_friend_id');
    }

    public function friends()
    {
        $acceptedFriends = $this->acceptedFriends()->latest()->get();
        $addedFriends = $this->addedFriends()->latest()->get();

        return $acceptedFriends->merge($addedFriends);
    }

    public function addFriend(User $user)
    {
        return $this->addedFriends()->save($user);
    }

    public function removeFriend(User $user)
    {
        return $this->addedFriends()->detach($user);
    }

    public function isFriend(User $user)
    {
        return (bool) $this->addedFriends()->where('added_friend_id', $user->id)->count() || $this->acceptedFriends()->where('user_id', $user->id)->count();
    }

    public function sendMessages()
    {
        return $this->hasMany(Message::class,
            'sender_id');
    }

    public function receivedMessages()
    {
        return $this->hasMany(Message::class,
            'receiver_id');
    }

    public function messagesTimelineByUser(User $user)
    {
        $sendMessagesToUser = $this->sendMessages()->where('receiver_id', $user->id)->latest()->get();
        $receivedMessagesByUser = $this->receivedMessages()->where('sender_id', $user->id)->latest()->get();

        $messages = $sendMessagesToUser->merge($receivedMessagesByUser);
        return $messages->sortBy('created_at');
    }

    public function isReceiver(Message $message)
    {
        return $message->receiver->id === $this->id;
    }

    public function roles()
    {
        return $this->belongsToMany(Role::class,
            'users_roles',
            'user_id',
            'role_id')->withTimestamps();
    }

    public function assignRole(Role $role)
    {
        return $this->roles()->save($role);
    }

    public function isAdmin()
    {
        return (bool) $this->roles()->where('role_id', 2)->count();
    }

    public function getRouteKeyName()
    {
        return 'username';
    }

    public function getImage()
    {
        return asset($this->image);
    }
}

GameBg/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function middleware($middleware, array $options = [])
    {
        return "admin";
    }

    public function destroy(User $user)
    {
        $this->authorize('destroy-user');

        $user->delete();

        if ($user->id === auth()->user()->id) {
            return redirect('games');
        }

        return back();
    }
}

GameBg/app/Http/Controllers/User/SearchUserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class SearchUserController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return void
     */
    public function index(Request $request)
    {
        $games = $request->input('games');

        $players = User::whereHas('games', function ($query) use ($games){
            $query->whereIn('games.slug', $games);
        })->get();

        return view('user/search-user/index', compact('players', 'games'));
    }
}

GameBg/app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UpdateUserBasicData;
use App\Http\Requests\UpdateUserPassword;
use App\User;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Gate;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function show(User $user)
    {
        return view('user/show', compact('user'));
    }

    public function edit(User $user)
    {
        $this->authorize('update-user', $user);

        return view('user/edit', compact('user'));
    }

    public function update(User $user, UpdateUserBasicData $request)
    {
        $attributes = $request->validated();

        if ($request->file('image')) {
            $attributes['image'] = $request->file('image')->store('profileImages');
        }

        $user->update($attributes);

        return $this->show($user);
    }
}

GameBg/app/Http/Controllers/User/UserFriendController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;

class UserFriendController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(User $user)
    {
        auth()->user()->addFriend($user);

        return back();
    }

    public function destroy(User $user)
    {
        auth()->user()->removeFriend($user);

        return back();
    }
}

GameBg/app/Http/Controllers/User/UserGameController.php
<?php

namespace App\Http\Controllers;

use App\Game;
use Illuminate\Auth\Access\Gate;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class UserGameController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function store(Game $game)
    {
        auth()->user()->addGame($game);

        return back();
    }

    public function destroy(Game $game)
    {
        auth()->user()->removeGame($game);

        return back();
    }
}

GameBg/app/Http/Controllers/User/UserMessageController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\StoreMessage;
use App\Message;
use App\User;
use Illuminate\Http\Request;

class UserMessageController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(User $user)
    {
        $this->authorize('store-message', $user);

        return view('user/user-message/index', compact('user'));
    }

    public function store(User $user, StoreMessage $request)
    {
        $attributes = $request->validated();

        Message::create([
            'sender_id' => auth()->user()->id,
            'receiver_id' => $user->id,
            'content' => $attributes['content']
        ]);

        return redirect(route('user.messages.index', $user->username));
    }
}

GameBg/resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-7">
                <div class="card m2">
                    <div class="card-header">Edit profile</div>
                    <div class="card-body text-center">
                        <form method="POST" action="{{route('user.update', $user->username)}}" enctype="multipart/form-data">
                            @csrf
                            @method("PUT");
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Username') }}</label>

                                <div class="col-md-6">
                                    <input id="name" value="{{$user->username}}" type="text" class="form-control @error('username') is-invalid @enderror" name="username" required autocomplete="name" autofocus>

                                    @error('username')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" value="{{$user->name}}" type="text" class="form-control @error('name') is-invalid @enderror" name="name" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" value="{{$user->email}}" type="email" class="form-control @error('email') is-invalid @enderror" name="email" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="image" class="col-md-4 col-form-label text-md-right">Profile image</label>

                                <div class="col-md-6">
                                    <input id="image" type="file" class="form-control" name="image">

                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        Edit
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

GameBg/resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            @include('user.user-game.index')
            <div class="col-md-8">
                <div class="card m2">
                    <div class="card-header">{{$user->username}}'s profile</div>
                    <div class="card-body text-center">
                        @if($user->image !== null)
                            <img class="rounded-circle" src="{{ $user->getImage() }}" width="125" height="125">
                        @endif
                        <h2 class="mt-3">{{$user->name}}</h2>
                        @can('update-user', $user)
                            <a class="btn btn-secondary" href="{{route('user.edit', $user->username)}}">Edit profile</a>
                                <a class="btn btn-secondary" href="{{route('user.password.edit', $user->username)}}">Change password</a>
                        @else
                            @if(auth()->user()->isFriend($user))
                                    <form method="post" action="{{route('user.friends.remove', $user->username)}}">
                                        @csrf
                                        @method("DELETE")
                                        <button type="submit">Remove from friends</button>
                                    </form>
                                    <form method="post" action="{{route('user.messages.add', $user->username)}}">
                                        @csrf
                                        <input type="text" name="content">
                                        <button type="submit">Send Message</button>
                                    </form>
                            @else
                                    <form method="post" action="{{route('user.friends.add', $user->username)}}">
                                        @csrf
                                        <button type="submit">Add to friends</button>
                                    </form>
                            @endif
                        @endcan
                    </div>
                </div>
            </div>
            @include('user.user-friend.index')
        </div>
    </div>
@endsection