GameBg/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@index')->name('home');

Auth::routes();

Route::resource('game', 'Admin\GameController', ['only' => ['create', 'store', 'edit', 'update', 'destroy']]);
Route::resource('game', 'GameController', ['only' => ['show', 'index']]);

Route::resource('user', 'UserController', ['only' => ['show', 'edit', 'update']]);
Route::resource('user', 'Admin\UserController', ['only' => ['destroy']]);

Route::resource('category', 'CategoryController', ['only' => ['store', 'update', 'destroy']]);

Route::post('/user/games/{game}/add', 'UserGameController@store')->name('user.games.add');
Route::delete('/user/games/{game}/remove', 'UserGameController@destroy')->name('user.games.remove');

Route::post('/user/friends/{user}/add', 'UserFriendController@store')->name('user.friends.add');
Route::delete('/user/friends/{user}/remove', 'UserFriendController@destroy')->name('user.friends.remove');

Route::post('/user/{user}/messages/add', 'UserMessageController@store')->name('user.messages.add');
Route::get('/user/{user}/messages', 'UserMessageController@index')->name('user.messages.index');

Route::get('/password/{user}/edit', 'ChangePasswordController@edit')->name('user.password.edit');
Route::put('/password/{user}/update', 'ChangePasswordController@update')->name('user.password.update');

Route::get('/search-user', 'SearchUserController@index')->name('user.search.index');

Route::get('/admin', 'AdminController@show')->name('admin.show');

GameBg/app/Game.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    protected $fillable = [
        "name", "description", "slug", "category_id"
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    // Relations
    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id');
    }

    public function players()
    {
        return $this->belongsToMany(User::class,
            'players_games',
            'game_id',
            'player_id');
    }

    public function images()
    {
        return $this->hasMany(GameImage::class, 'game_id');
    }

    // Helper functions
    public function isPlayedBy(User $user)
    {
        return (bool)$this->players()->where('player_id', $user->id)->count();
    }

    public function mainImage()
    {
        return $this->images()->where('is_main_image', true)->first();
    }
}

GameBg/app/Http/Controllers/Admin/GameController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Category;
use App\Game;
use App\GameImage;
use App\Http\Controllers\Controller;
use App\Http\Requests\StoreGame;
use App\Http\Requests\UpdateGame;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class GameController extends Controller
{

    public function middleware($middleware, array $options = [])
    {
        return 'admin';
    }

    public function destroy(Game $game)
    {
        $this->authorize('destroy-game');

        $game->delete();

        return back();
    }

    public function create()
    {
        $this->authorize('store-game');

        $categories = Category::all();

        return view('admin/game/create', compact('categories'));
    }

    public function store(StoreGame $request)
    {
        $attributes = $request->validated();

        $game = Game::create([
            'name' => $attributes['name'],
            'description' => $attributes['description'],
            'category_id' => $attributes['category'],
            'slug' => Str::slug($attributes['name'], '-')
        ]);

        foreach ($attributes['images'] as $image) {
            GameImage::create([
                'image' => Storage::disk('public')->put('games', $image),
                'game_id' => $game->id,
                'is_main_image' => GameImage::where('game_id', $game->id)->get()->count() < 1 ? true : false
            ]);
        }

        return redirect(route('admin.show'));
    }

    public function edit(Game $game)
    {
        $this->authorize('update-game');

        $categories = Category::all();

        return view('admin/game/edit', compact('game', 'categories'));
    }

    public function update(Game $game, UpdateGame $request)
    {
        $attributes = $request->validated();

        $attributes['slug'] = Str::slug($attributes['name'], '-');
        $game->update($attributes);

        if ($request->file('images')) {
            foreach ($attributes['images'] as $imageId => $imageURL) {
                $gameImage = GameImage::find($imageId);
                $gameImage->image = Storage::disk('public')->put('games', $imageURL);

                $gameImage->update();
            }
        }

        return redirect(route('admin.show'));
    }
}

GameBg/app/Http/Controllers/GameController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Game;
use App\GameImage;
use App\Http\Requests\StoreGame;
use App\Http\Requests\UpdateGame;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class GameController extends Controller
{
    public function index()
    {
        $games = Game::with('category')->get();
        $user = auth()->user();

        return view('game/index',
            compact('games', 'user')
        );
    }

    public function show(Game $game)
    {
        return view('game/show', compact('game'));
    }
}

GameBg/resources/views/game/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        @auth
            @include('user.user-game.index')
        @endauth
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">All Games</div>

                <div class="card-body text-center">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    @foreach($games as $game)
                            <p>{{$game->name}}</p>
                            <p> Category: <img class="rounded-circle" src="{{ $game->category->getImage() }}" width="25" height="25"> {{$game->category->name}}</p>
                            <a class="btn btn-info btn-sm mb-2" href="{{route('game.show', $game->slug)}}">View game</a>
                            @auth()
                                @if(!$game->isPlayedBy(auth()->user()))
                                    <form method="post" action="{{route('user.games.add', $game->slug)}}">
                                        @csrf
                                        <button type="submit">I play this</button>
                                    </form>
                                @else
                                    <form method="post" action="{{route('user.games.remove', $game->slug)}}">
                                        @method("delete")
                                        @csrf
                                        <button type="submit">I don't play this anymore</button>
                                    </form>
                                @endif
                            @endauth
                        <hr>
                    @endforeach
                </div>
            </div>
        </div>
            @auth()
                <div class="col-md-2">
                    <div class="card">
                        <div class="card-header">Search buddy</div>
                        <div class="card-body text-center">
                            <form method="GET" action="{{route('user.search.index')}}">
                                @csrf
                                <label for="games">Choose a game:</label>
                                <select name="games[]" multiple="multiple">
                                    @foreach($games as $game)
                                        <option value="{{$game->slug}}">{{$game->name}}</option>
                                    @endforeach
                                </select>
                                <br><br>
                                <input type="submit" value="Submit">
                            </form>
                        </div>
                    </div>
                </div>
            @endauth

    </div>
</div>
@endsection

GameBg/resources/views/game/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{$game->name}}</div>
                    <div class="card-body text-center">
                        <img class="rounded mb-2" src="{{ $game->mainImage()->getImage() }}" width="100" height="100">
                        <h2> <b>{{$game->name}}</b> </h2>

                        <p>{{$game->description}}</p>
                        <h4><b>Game Images:</b></h4>
                        @foreach($game->images as $image)
                            @if(!$image->is_main_image)
                                <img class="rounded" src="{{ $image->getImage() }}" width="100" height="100">
                            @endif
                        @endforeach
                        @auth()
                            @if(!$game->isPlayedBy(auth()->user()))
                                <form method="post" action="{{ route('user.games.add', $game->slug) }}">
                                    @csrf
                                    <button class="mt-3" type="submit" >I play this</button>
                                </form>
                            @else
                                <form method="post" action="{{ route('user.games.remove', $game->slug) }}">
                                    @method("delete")
                                    @csrf
                                    <button class="mt-3" type="submit">I don't play this anymore</button>
                                </form>
                            @endif
                                <form method="GET" action="{{route('user.search.index')}}">
                                    @csrf
                                    <input type="hidden" name="games[]" value="{{$game->slug}}">
                                    <input class="mt-2" type="submit" value="People who play this game">
                                </form>
                            @if(auth()->user()->isAdmin())
                                <a class="btn btn-info mt-2" href="{{route('game.edit', $game->slug)}}">Edit Game</a>
                            @endif
                        @endauth
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection