GameBg/routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'GameController@index')->name('home');

Auth::routes();

Route::resource('game', 'Admin\GameController', ['only' => ['create', 'store', 'edit', 'update', 'destroy']]);
Route::resource('game', 'GameController', ['only' => ['show', 'index']]);

Route::resource('user', 'UserController', ['only' => ['show', 'edit', 'update']]);
Route::resource('user', 'Admin\UserController', ['only' => ['destroy']]);

Route::resource('category', 'CategoryController', ['only' => ['store', 'update', 'destroy']]);

Route::post('/user/games/{game}/add', 'UserGameController@store')->name('user.games.add');
Route::delete('/user/games/{game}/remove', 'UserGameController@destroy')->name('user.games.remove');

Route::post('/user/friends/{user}/add', 'UserFriendController@store')->name('user.friends.add');
Route::delete('/user/friends/{user}/remove', 'UserFriendController@destroy')->name('user.friends.remove');

Route::post('/user/{user}/messages/add', 'UserMessageController@store')->name('user.messages.add');
Route::get('/user/{user}/messages', 'UserMessageController@index')->name('user.messages.index');

Route::get('/password/{user}/edit', 'ChangePasswordController@edit')->name('user.password.edit');
Route::put('/password/{user}/update', 'ChangePasswordController@update')->name('user.password.update');

Route::get('/search-user', 'SearchUserController@index')->name('user.search.index');

Route::get('/admin', 'AdminController@show')->name('admin.show');

GameBg/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $fillable = [
        "name", "image", "slug"
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    // Relations
    public function games()
    {
        return $this->hasMany(Game::class, 'category_id');
    }

    // Helper functions
    public function getImage()
    {
        return asset($this->image);
    }
}

GameBg/app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\StoreCategory;
use App\Http\Requests\UpdateCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CategoryController extends Controller
{
    public function __construct()
    {
        $this->middleware('admin');
    }

    public function store(StoreCategory $request)
    {
        $attributes = $request->validated();

        Category::create([
            'name' => $attributes['name'],
            'image' => Storage::disk('public')->put('categories', $attributes['image']),
            'slug' => Str::slug($attributes['name'], '-')
        ]);

        return back();
    }

    public function update(Category $category, UpdateCategory $request)
    {
        $attributes = $request->validated();

        $attributes['slug'] = Str::slug($attributes['name'], '-');

        if ($request->file('image')) {
            $attributes['image'] = Storage::disk('public')->put('categories', $request->file('image'));
        }

        $category->update($attributes);

        return back();
    }

    public function destroy(Category $category)
    {
        $category->delete();

        return back();
    }
}

GameBg/resources/views/admin/category/create.blade.php
<div class="modal fade" id="createCategoryModal" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Create category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{route('category.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="modal-body">
                    <input type="text" name="name" required>
                    @error("name")
                    <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                    @enderror
                    <input id="image" type="file" class="form-control" name="image" required>

                    @error('image')
                    <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                    @enderror
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Create</button>
                </div>
            </form>
        </div>
    </div>
</div>

GameBg/resources/views/admin/category/edit.blade.php
<div class="modal fade" id="editCategoryModal{{$category->slug}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Edit "{{$category->name}}" category</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form method="POST" action="{{route('category.update', $category->slug)}}" enctype="multipart/form-data">
                @csrf
                @method("PUT")
                <div class="modal-body">
                    <input type="text" name="name" value="{{$category->name}}" required>
                    @error("name")
                    <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                    @enderror
                    <input type="file" class="form-control" name="image">

                    @error('image')
                    <span class="invalid-feedback" role="alert">
                                                <strong>{{ $message }}</strong>
                                            </span>
                    @enderror
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Edit</button>
                </div>
            </form>
        </div>
    </div>
</div>

GameBg/resources/views/admin/category/index.blade.php
<div class="col-md-2">
    <div class="card-header">Categories <a class="btn btn-sm btn-info text-center"  data-toggle="modal" data-target="#createCategoryModal">Create category</a></div>
    <div class="card-body">
        @foreach($categories as $category)
            <p><img class="rounded-circle" src="{{$category->getImage()}}" width="30" height="30"><b> {{$category->name}}</b></p>
            <a class="btn btn-sm btn-info text-center" data-toggle="modal" data-target="#editCategoryModal{{$category->slug}}">Edit</a>
            <form method="POST" action="{{route('category.destroy', $category->slug)}}">
                @csrf
                @method("DELETE")
                <button type="submit" class="btn btn-sm btn-danger text-center">Delete</button>
            </form>
            <hr>
            @include('admin.category.edit')
        @endforeach
    </div>
</div>